2016-11-28 22:17:18 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/citedDocuments?DB=EPODOC&II=24&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161123&CC=EP&NR=3095329A1&KC=A1> (referer: https://worldwide.espacenet.com/data/publicationDetails/claims?DB=EPODOC&II=24&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161123&CC=EP&NR=3095329A1&KC=A1)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 381, in parse_cited_tab
    entry = record + ' ' + inventors[i] + ' ' + applicants[i] + ' ' + CPC[i] + ' ' + IPC[i] + ' ' + pub_info[i] + ' ' + priority_date[i] + '\n'
IndexError: list index out of range
2016-11-28 22:19:21 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/data/publicationDetails/citedDocuments?DB=EPODOC&II=21&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161123&CC=EP&NR=3096499A1&KC=A1> (referer: https://worldwide.espacenet.com/data/publicationDetails/claims?DB=EPODOC&II=21&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161123&CC=EP&NR=3096499A1&KC=A1)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 381, in parse_cited_tab
    entry = record + ' ' + inventors[i] + ' ' + applicants[i] + ' ' + CPC[i] + ' ' + IPC[i] + ' ' + pub_info[i] + ' ' + priority_date[i] + '\n'
IndexError: list index out of range
2016-11-28 22:24:51 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/publicationDetails/citingDocuments?DB=EPODOC&II=17&ND=3&adjacent=true&locale=en_EP&FT=D&date=20161109&CC=EP&NR=3091315A1&KC=A1)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 524, in parse_inpadoc_tab
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:26:35 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=399&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:26:43 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=399&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:26:47 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=399&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:26:52 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=399&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:26:57 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=399&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:27:05 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=399&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:27:09 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=33&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:27:15 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=33&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:27:21 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=33&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:27:25 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=33&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:27:32 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=33&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:27:37 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=33&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:27:44 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=33&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:27:50 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=33&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:27:55 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=33&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:28:00 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=33&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:29:45 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=33&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:29:49 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=33&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:29:54 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=33&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:30:01 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=33&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:30:06 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=33&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:30:12 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=33&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:30:19 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=33&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:30:25 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=33&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:30:30 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=33&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:30:34 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=33&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:30:42 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=33&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:30:49 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=33&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:30:56 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=33&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:31:03 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=33&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:31:10 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=34&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:31:17 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=34&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:33:08 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=34&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:33:13 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=34&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:33:21 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=34&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:33:25 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=34&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:33:30 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=34&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:33:34 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=34&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:33:40 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=34&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:33:46 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=34&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:33:53 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=34&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:34:01 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=34&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:34:08 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=34&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:34:15 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=34&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:34:19 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=34&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:34:25 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=34&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:34:31 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=34&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:34:37 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=34&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:36:24 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=34&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:36:28 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=34&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:36:34 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=34&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:36:40 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=34&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:36:47 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=34&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:36:53 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=34&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:37:00 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=35&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:37:08 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=35&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
2016-11-28 22:37:13 [scrapy] ERROR: Spider error processing <GET https://worldwide.espacenet.com/errorpages/error403.htm?reason=DataSizeQuota&ip=31.50.200.73> (referer: https://worldwide.espacenet.com/data/searchResults?page=35&locale=en_EP&DB=EPODOC&ST=advanced&TI=&AB=&PN=EP&AP=&PR=&PD=&PA=&IN=&CPC=&IC=&Submit=Search)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\scrapy\utils\defer.py", line 102, in iter_errback
    yield next(it)
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\offsite.py", line 29, in process_spider_output
    for x in result:
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\referer.py", line 22, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "c:\python27\lib\site-packages\scrapy\spidermiddlewares\depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "C:\Users\serap\Documents\inventtory_data_scraping\inventtory_data_scraping\inventtory_spiders\inventtory_spiders\spiders\ww_espacenet_europe.py", line 85, in parse_patent_link
    url1 = re.match('(https:\/\/worldwide\.espacenet\.com\/data\/publicationDetails\/)\w+(\?.*)',url).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
